version: '2.2'
services:
  db:
    image: postgres
    restart: always
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - /home/luisma/data/postgres:/var/lib/postgresql/data
